### ISSUE TITLE
Constraints in `ttnn.pad` to support lowering `aten.constantpad_nd`

### ISSUE THREAD

**Issue by jerrysky3** [tenstorrent/pytorch2.0_ttnn#176]
When trying to lower `aten.constantpad_nd` to `ttnn.pad`, I ran into several constraints of the `ttnn.pad`

1. With the input shape `(16, 16)` and the padding size `[(0, 0), (0, 16)]` (the result shape is `(16, 32)`), there is an error:

```
 RuntimeError: TT_FATAL @ /home/runner/work/tt-metal/tt-metal/tt_metal/impl/buffers/buffer.cpp:38: valid_page_size
```

2. With the input shape `(3, 1)` and the padding size `[(0, 1), (0, 1)]` (the result shape is `(4, 2)`), it triggers the assertion:

```
# RuntimeError: TT_FATAL @ /home/runner/work/tt-metal/tt-metal/ttnn/cpp/ttnn/operations/data_movement/pad/pad.cpp:102: target_height % ttnn::TILE_SIZE == 0 || target_width % ttnn::TILE_SIZE == 0
        # info:
        # ttnn.pad: for tiled tensors padding end must be a multiple of the tile size on height and width for a tensor in tile layout
```

3. With the input shape `(1, 32)` and the padding size `[(0, 0), (0, 32)]`, the result shape should be `(1, 64)` but `ttnn.pad` outputs `(32, 64)`

4. With the input shaoe `(32, 32)` and the padding size `[(32, 0), (32, 0)]` (the result shape is `(64, 64)`), it triggers the assertion:

```
RuntimeError: TT_FATAL @ /home/runner/work/tt-metal/tt-metal/ttnn/cpp/ttnn/operations/data_movement/pad/pad.cpp:93: front_padding_is_zero
```

For 1., I'm not familiar with ttnn enough but it seems to have certain constraints on buffer layout

For 2. and 3., it seems like `ttnn.pad` can only pad into shapes that align with `ttnn.TILE_SIZE` (32 in this case). I can try to pad to aligned sizes and slice the result back to the expected output shape.

For 4., it looks like `ttnn.pad` doesn't support padding in the front. Not very sure how to handle this case, maybe it's possible to allocate a new tensor and copy the inupt tensor to the middle?

**Comment by ayerofieiev-tt** [comment]
@jerrysky3 please make yourself familiar with this tech report

https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/tensor_layouts/tensor_layouts.md

**Comment by jerrysky3** [comment]
> @jerrysky3 please make yourself familiar with this tech report
> 
> https://github.com/tenstorrent/tt-metal/blob/main/tech_reports/tensor_layouts/tensor_layouts.md
> 
> Please ask any questions

Thanks! I read the doc and was able to solve majority of questions here by fallback to pad in `ROW_MAJOR` layout. There is a strange issue with front padding when length < 16. I filed #192 for it and I think this issue can be closed.
