### ISSUE TITLE
aten.view's err value too large on integer type

### ISSUE THREAD

**Issue by swimdi** [tenstorrent/pytorch2.0_ttnn#420]
In `microsoft/beit-base-patch16-224`, there has this pattern
```
view_13 = torch.ops.aten.view.default(arg223_1, [-1])
index = torch.ops.aten.index.Tensor(arg1_1, [view_13])
```
where `arg1_1.shape = [732, 12]` and `arg223_1` will to be a list of index
```
tensor([[731, 729, 729,  ..., 729, 729, 729],
        [730, 364, 363,  ...,   2,   1,   0],
        [730, 365, 364,  ...,   3,   2,   1],
        ...,
        [730, 726, 725,  ..., 364, 363, 362],
        [730, 727, 726,  ..., 365, 364, 363],
        [730, 728, 727,  ..., 366, 365, 364]])
```
`arg223_1` dtype is `int64`, and value 731 is contained in it, and
 - if `arg223_1` become `view_13` by `torch.ops.aten.view.default`, then value 731 retain 731
 - if `arg223_1` become `view_13` by `ttnn.reshape`, then because `ttnn.reshape` input dtype must be bfloat16, then value 731 should be converted to `bfloat16(731) = 732`, and convert back to `int64(732) = 732` after `ttnn.reshape`, so the value 731 become 732 in `view_13`, then it will casue this error
```
IndexError: index 732 is out of bounds for dimension 0 with size 732
```

One of the suggestion of this issue is NOT lowering `torch.ops.aten.view.default` to `ttnn.reshape` if dtype is `int64`(then beit cannot end-to-end compiled), but I want to get some feedback from TT side

You can reproduce this error by `pytest tests/pattern/test_beit_pattern.py`

**Comment by ayerofieiev-tt** [comment]
Got it. Checking with the team. If we truly can’t support int64 in reshape, I agree, we should avoid.

**Comment by ayerofieiev-tt** [comment]
@swimdi the team reports that this op must support integer types no problem

Please consult with @kevinwuTT if you want to try maintaining the dtype.
I think this issue must remain on Skymizer.

@ntarafdar FYI

**Comment by swimdi** [comment]
Afterward I found this reason maybe is `add_data_move_pass.py` force `ttnn.from_torch` with `bfloat16` dtype before `ttnn.reshape`

I think I will refactor the `add_data_move_pass.py` and resolved this force convert bfloat16 dtype issue

BTW, I found some value for indexing is not only go trhough `ttnn.reshape`, for example, [ssd300_vgg16 has this chain](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/b3f7e0e7f729ba46e2070b2dd2720e3afe51c5f0/torch_ttnn/passes/lowering/to_tt_guard.py#L325-L333)
```
arange(300) => add(0.5) => mul(1.6) => sub(0.5) => clamp(0.0) => to_copy(int64) => unsqueeze => unsafe_index
```
In this case, even if I block `unsqueeze` not lowering to `ttnn.reshape`, there still has error
```
IndexError: index 480 is out of bounds for dimension 0 with size 480
```
I think in this case, if `ttnn.add/mul/sub` cannot inference with float type, the err value will still too large...

**Comment by swimdi** [comment]
I solved in this commit

https://github.com/tenstorrent/pytorch2.0_ttnn/pull/533/commits/c1128916c79989f44d327500e3ffaa54f3d3cb55

But also another issue come across

The input of `ttnn.reshape` will not force convert to bfloat16, but in `yolos`, has this pattern
```
a = ttnn.from_torch(1.0, dtype = ttnn.bfloat16)
b = ttnn.from_torch(2) # dtype = ttnn.uint32
reshape = ttnn.reshape(b) # dtype = ttnn.uint32
c = ttnn.mul(a, b)

# input_tensor_a.get_dtype() == DataType::BFLOAT16 or input_tensor_a.get_dtype() == DataType::FLOAT32
```
Can ttnn.add/sub/mul/div support the case if one input dtype is bfloat16 and another input dtype is uint32?
