### ISSUE TITLE
aten.t.default

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/pytorch2.0_ttnn#439]

**Comment by jerrysky3** [comment]
Considered it is done with workaround for now. The follow-up improvement is tracked in #377

**Comment by ayerofieiev-tt** [comment]
@jerrysky3 , please take a look at this comment
https://github.com/tenstorrent/pytorch2.0_ttnn/issues/377#issuecomment-2489911960

Transpose recently got improved and Row Major tensor with odd # of elements on width in bfloat16 is not supported nicely.
Switching to Transpose is an option now.

**Comment by jerrysky3** [comment]
> [@jerrysky3](https://github.com/jerrysky3) , please take a look at this comment [#377 (comment)](https://github.com/tenstorrent/pytorch2.0_ttnn/issues/377#issuecomment-2489911960)
> 
> Transpose recently got improved and Row Major tensor with odd # of elements on width in bfloat16 is not supported nicely. Switching to Transpose is an option now.

Oh I see. I misread the comment. Yes, tested with `ttnn.transpose` and all cases are passed now, will send a PR

**Comment by jerrysky3** [comment]
Sent out the PR to use `ttnn.transpose` https://github.com/tenstorrent/pytorch2.0_ttnn/pull/500
