### ISSUE TITLE
Unsqueeze fails to unsqueeze [10] to [10, 1] and [1, 64] to [1, 64, 1] in Tile Layout

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/pytorch2.0_ttnn#468]

**Comment by jvegaTT** [comment]
This will definitely fail with the current implementation (it's tiled right?) As the configuration is illegal in RM. I will address this case in the new stuff I'm building but in the meantime this falls under the cases that could be done as a transpose I believe. I haven't seen updates from the team that was handling this.

**Comment by ayerofieiev-tt** [comment]
> As the configuration is illegal in RM
Not as of this night!

**Comment by swimdi** [comment]
Solved in #450
