### ISSUE TITLE
aten._adaptive_avg_pool2d.default

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/pytorch2.0_ttnn#475]

**Comment by swimdi** [comment]
Need to solved https://github.com/tenstorrent/tt-metal/issues/12151 or the `ttnn.avg_pool2d` cannot support case of `output_size != [1, 1]`
```
input = torch.randn([1, 512, 7, 7]).to(torch.bfloat16)
output_size = [7, 7]
adaptive_avg_pool2d = torch.ops.aten._adaptive_avg_pool2d.default(input, output_size)
print(adaptive_avg_pool2d.shape)
# torch.Size([1, 512, 7, 7])
```

**Comment by swimdi** [comment]
Sorry the above comment is wrong, please ignore it

Here is the description of `aten._adaptive_avg_pool2d.default`:

`aten._adaptive_avg_pool2d.default` is not same with `aten.avg_pool2d.default`, but it can [convert to `aten.avg_pool2d.default`](https://stackoverflow.com/questions/58692476/what-is-adaptive-average-pooling-and-how-does-it-work) by mapping `aten._adaptive_avg_pool2d.default`'s `output_size` argument to `aten.avg_pool2d.default`'s `stride` & `size` by

```
Stride = (input_size//output_size)  
Kernel size = input_size - (output_size-1)*stride  
Padding = 0
```

So if want to support lowering of `aten._adaptive_avg_pool2d.default`, then it needs either `ttnn.adaptive_avg_pool2d` op for direct converting or `ttnn.avg_pool2d` with above adjust

But seems there no `ttnn.adaptive_avg_pool2d` op now, and `ttnn.avg_pool2d` is not finished according to https://github.com/tenstorrent/tt-metal/issues/12151

Luckly, there's [only one input variation](https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/docs/operations/aten._adaptive_avg_pool2d.default.md) appeared on models
```
Tensor<[1, 512, 7, 7]> self = ?, List[int] output_size = [7, 7]
```
And this input variation actually let `aten._adaptive_avg_pool2d.default` do nothing, so if we check these input varation type during lowering and just remove it, then we can say `aten._adaptive_avg_pool2d.default` is fully supported of the current scope of models
