### ISSUE TITLE
aten.div.Tensor

### ISSUE THREAD

**Issue by ayerofieiev-tt** [tenstorrent/pytorch2.0_ttnn#479]

**Comment by jdh8** [comment]
Reopening this issue to deal with the block list

https://github.com/tenstorrent/pytorch2.0_ttnn/blob/055bef3f8d896defbad47a2bdda72f093c40e028/torch_ttnn/passes/lowering/to_tt_guard_autogen.py#L138-L159

**Comment by ayerofieiev-tt** [comment]
@jdh8 , this must be a bcast mismatch, wdyt?
```
     ["Tensor<[1, 23, 40, 1]> self = ?", "Tensor<[128]> other = ?"], 
```
